# Generated by Django 5.1.5 on 2025-02-01 09:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('question', models.TextField(
                    help_text='Enter the question in English',
                    verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(
                    help_text='Enter the answer in English',
                    verbose_name='Answer')),
                ('question_hi', models.TextField(
                    blank=True,
                    help_text='Enter the Hindi translation of the question',
                    verbose_name='Question (Hindi)')),
                ('answer_hi', ckeditor.fields.RichTextField(
                    blank=True,
                    help_text='Enter the Hindi translation of the answer',
                    verbose_name='Answer (Hindi)')),
                ('question_bn', models.TextField(
                    blank=True,
                    help_text='Enter the Bengali translation of the question',
                    verbose_name='Question (Bengali)')),
                ('answer_bn', ckeditor.fields.RichTextField(
                    blank=True,
                    help_text='Enter the Bengali translation of the answer',
                    verbose_name='Answer (Bengali)')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    null=True,
                    blank=True)),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    null=True,
                    blank=True)),
                ('is_active', models.BooleanField(
                    default=True,
                    help_text='Toggle to show/hide this FAQ',
                    verbose_name='Active')),
                ('order', models.PositiveIntegerField(
                    default=0,
                    help_text='Order in which this FAQ should be displayed',
                    verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
