# Generated by Django 5.1.5 on 2025-02-01 12:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='order',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_bn',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Bengali)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_hi',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Hindi)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_bn',
            field=models.TextField(
                blank=True,
                verbose_name='Question (Bengali)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_hi',
            field=models.TextField(
                blank=True,
                verbose_name='Question (Hindi)'),
        ),
    ]
