# Generated by Django 5.1.5 on 2025-02-01 13:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_options_remove_faq_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_gu',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Gujarati)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_kn',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Kannada)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ml',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Malayalam)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_my',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Burmese)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_or',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Oriya)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_si',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Sinhala)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ta',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Tamil)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_te',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Telugu)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_gu',
            field=models.TextField(
                blank=True,
                verbose_name='Question (Gujarati)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_kn',
            field=models.TextField(
                blank=True,
                verbose_name='Question (Kannada)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ml',
            field=models.TextField(
                blank=True,
                verbose_name='Question (Malayalam)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_my',
            field=models.TextField(
                blank=True,
                verbose_name='Question (Burmese)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_or',
            field=models.TextField(
                blank=True,
                verbose_name='Question (Oriya)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_si',
            field=models.TextField(
                blank=True,
                verbose_name='Question (Sinhala)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ta',
            field=models.TextField(
                blank=True,
                verbose_name='Question (Tamil)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_te',
            field=models.TextField(
                blank=True,
                verbose_name='Question (Telugu)'),
        ),
    ]
