# Generated by Django 5.1.5 on 2025-02-02 06:46

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_answer_gu_faq_answer_kn_faq_answer_ml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_or',
            field=ckeditor.fields.RichTextField(
                blank=True,
                verbose_name='Answer (Odia)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_or',
            field=models.TextField(blank=True, verbose_name='Question (Odia)'),
        ),
    ]
