# Generated by Django 5.1.5 on 2025-02-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_remove_faq_answer_my_remove_faq_answer_or_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_ml',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ml',
        ),
    ]
